name: Android APK Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Android SDK manually
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm cmdline-tools.zip
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64"

      # Create AVD
      - name: Create AVD
        run: |
          echo no | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd \
            --force \
            --name test \
            --package "system-images;android-30;google_apis;x86_64" \
            --device "Nexus 5" \
            --abi "x86_64"

      # Start emulator
      - name: Start emulator
        run: |
          $ANDROID_SDK_ROOT/emulator/emulator \
            -avd test \
            -no-audio \
            -no-boot-anim \
            -no-window \
            -gpu swiftshader_indirect \
            -memory 2048 \
            -partition-size 2048 \
            -netspeed full \
            -netdelay none \
            -verbose \
            -qemu -m 2048 -enable-kvm &
          echo "Emulator started in background"

      # Wait for emulator to boot
      - name: Wait for emulator
        run: |
          adb wait-for-device
          while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
            sleep 5
            echo "Waiting for emulator to boot..."
          done
          echo "Emulator booted successfully"

      # Install APK
      - name: Install APK
        run: |
          adb install -t -g ./Krishivaas_Farmer.apk
          echo "APK installed successfully"

      # Run tests
      - name: Run tests
        working-directory: ./test
        run: |
          npm install
          npm run test

      # Collect results
      - name: Collect results
        if: always()
        run: |
          mkdir -p allure-results
          adb pull /sdcard/Download/allure-results ./allure-results || echo "No results found"