name: Android CI Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Extended timeout

    steps:
      - uses: actions/checkout@v4

      # Java Environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Node Environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Dependencies
      - name: Install npm packages
        run: npm install

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate with Firebase
      - name: Authenticate with Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
          gcloud auth activate-service-account --key-file=firebase-service-account.json
          gcloud config set project <YOUR_FIREBASE_PROJECT_ID>

      # Build APK for Testing
      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug
          ./gradlew assembleAndroidTest

      # Run Firebase Test Lab Tests
      - name: Run Firebase Test Lab
        run: |
          gcloud firebase test android run \
            --app app/build/outputs/apk/debug/app-debug.apk \
            --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=Pixel6,version=34,locale=en,orientation=portrait \
            --results-dir=allure-results

      # Install Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean

      # Upload Allure Report as Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      # Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true

      # Cleanup
      - name: Clean Up
        if: always()
        run: rm -f firebase-service-account.json
