name: Android APK Testing
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Android SDK setup with specific versions
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          emulator: true
          api-level: 31
          build-tools: 31.0.0
          platform: android-31
          cmdline-tools: '8.0'  # Specific version to avoid XML issues
          ndk: none
          cmake: none

      # Configure environment
      - name: Set up Android environment
        run: |
          echo "$ANDROID_SDK_ROOT/emulator" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/8.0/bin" >> $GITHUB_PATH
          mkdir -p ~/.android/avd
          echo "ANDROID_AVD_HOME=$HOME/.android/avd" >> $GITHUB_ENV

      # Clear SDK cache to prevent XML version conflicts
      - name: Clean SDK cache
        run: |
          sdkmanager --uninstall "cmdline-tools;latest" || true
          sdkmanager --install "cmdline-tools;8.0"

      # Install system image with retries
      - name: Install system image
        run: |
          yes | sdkmanager --licenses
          for i in {1..3}; do
            if sdkmanager "platform-tools" "emulator" "system-images;android-31;google_apis;x86_64"; then
              break
            fi
            echo "Attempt $i failed, retrying..."
            sleep 10
          done

      # Create AVD with proper formatting
      - name: Create AVD
        run: |
          # Get device list and select pixel_4 explicitly
          device_id=$(avdmanager list device | grep -A 5 "pixel_4" | grep "id:" | awk '{print $2}' | head -1)
          
          echo "Creating AVD with device ID: $device_id"
          avdmanager create avd \
            --name test_avd \
            --package "system-images;android-31;google_apis;x86_64" \
            --device "$device_id" \
            --force
          
          # Verify AVD creation
          emulator -list-avds
          ls -la ~/.android/avd/

      # Start emulator with hardware acceleration
      - name: Start emulator
        run: |
          echo "Starting emulator..."
          emulator -avd test_avd \
            -no-window \
            -no-audio \
            -no-snapshot \
            -memory 2048 \
            -gpu swiftshader_indirect \
            -no-boot-anim \
            -partition-size 2048 &
          
          # Wait for device with timeout
          timeout 300 adb wait-for-device
          
          # Check boot completion
          for i in {1..60}; do
            if adb shell getprop sys.boot_completed | grep -q "1"; then
              echo "Emulator ready after $i seconds"
              break
            fi
            sleep 2
          done

      # Rest of your workflow steps...
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g appium@next
          npm install
          npm install -g allure-commandline

      - name: Install APK
        run: |
          adb install -t -g ./Krishivaas_Farmer.apk
          adb shell pm list packages | grep com.krishivaas

      - name: Run Tests
        env:
          APPIUM_PORT: 4723
        run: |
          nohup appium --log-level info --relaxed-security > appium.log 2>&1 &
          sleep 15
          npx wdio run wdio.conf.js || true
          mkdir -p test-results
          cp appium.log test-results/
          adb logcat -d > test-results/logcat.log

      - name: Process results
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
          if grep -q "failed" wdio.log; then
            echo "::warning::Some tests failed"
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            allure-report/
            test-results/
            wdio.log

      - name: Clean up
        if: always()
        run: |
          adb emu kill || true
          pkill -f "emulator" || true