name: Android APK Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK with specific versions to avoid XML warnings
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '8.0'  # Older but more stable version
          build-tools-version: '30.0.3'
          platform-version: '30'
          emulator-version: '31.3.13'  # Known stable version
          ndk-version: 'none'

      # Accept licenses
      - name: Accept licenses
        run: |
          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager --update

      # Install system image
      - name: Install system image
        run: |
          sdkmanager "system-images;android-30;google_apis;x86_64"
          echo "System image installed"

      # Create AVD with more stable configuration
      - name: Create AVD
        run: |
          echo no | avdmanager create avd \
            --force \
            --name test \
            --package "system-images;android-30;google_apis;x86_64" \
            --device "Nexus 5" \
            --abi "x86_64"
          echo "AVD created successfully"

      # Start emulator with proper settings
      - name: Start emulator
        run: |
          $ANDROID_SDK_ROOT/emulator/emulator \
            -avd test \
            -no-audio \
            -no-boot-anim \
            -no-window \
            -gpu swiftshader_indirect \
            -accel off \
            -memory 2048 \
            -partition-size 2048 \
            -netspeed full \
            -netdelay none \
            -verbose \
            -qemu -m 2048 -enable-kvm &
          echo "Emulator started in background"

      # Wait for emulator to boot
      - name: Wait for emulator
        run: |
          adb wait-for-device
          while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
            sleep 5
            echo "Waiting for emulator to boot..."
          done
          echo "Emulator booted successfully"

      # Install APK
      - name: Install APK
        run: |
          adb install -t -g ./Krishivaas_Farmer.apk
          echo "APK installed successfully"

      # Run tests
      - name: Run tests
        working-directory: ./test
        run: |
          npm install
          npm run test

      # Collect results
      - name: Collect results
        if: always()
        run: |
          mkdir -p allure-results
          adb pull /sdcard/Download/allure-results ./allure-results || echo "No results found"