name: Run Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Set up Android SDK
        run: |
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          emulator-boot-timeout: 600
          script: echo "Emulator setup complete"

      - name: Wait for Emulator
        run: |
          adb wait-for-device
          adb shell input keyevent 82
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 2; done'

      - name: Run tests
        run: npx wdio run wdio.conf.js

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Deploy Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report