name: Android APK Testing with Firebase Test Lab and Allure
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js for Allure
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Allure
        run: npm install -g allure-commandline

      # Set up Google Cloud SDK and authenticate with Firebase service account
      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
          gcloud auth activate-service-account --key-file=firebase-service-account.json
          gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      # Prepare APKs
      - name: Prepare APKs
        run: |
          cp "./Krishivaas_Farmer.apk" ./app.apk

      # Create directory for Allure results
      - name: Create Allure Directory
        run: mkdir -p ./allure-results

      # Run tests on Firebase Test Lab with Allure results
      - name: Run Firebase Test Lab with Allure
        run: |
          # Run tests on Firebase Test Lab
          gcloud firebase test android run \
            --type instrumentation \
            --app ./app.apk \
            --test ./test.apk \
            --device model=Pixel2,version=30,locale=en,orientation=portrait \
            --environment-variables clearPackageData=true \
            --directories-to-pull=/sdcard/Download/allure-results \
            --timeout 20m \
            --no-results-bucket  # This skips GCS storage

          # The results will be in the working directory after test completion
          # Firebase Test Lab automatically downloads them when --no-results-bucket is used

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: |
          # Find and move the downloaded allure results
          find . -name "allure-results" -exec cp -r {} ./allure-results \;
          allure generate ./allure-results --clean -o ./allure-report

      # Upload Allure Report as Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      # Optional: Commit and push the Allure results
      - name: Commit Allure Results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add allure-results/
          git commit -m "Add latest Allure test results" || echo "No changes to commit"
          git push || echo "Nothing to push"