name: Android APK Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js for test project
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          working-directory: './test'

      # Install test project dependencies
      - name: Install dependencies
        run: npm install
        working-directory: './test'

      # Set up Android environment
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Start emulator
      - name: Launch Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 5
          disable-animations: true
          script: |
            adb wait-for-device
            echo "Installing production APK..."
            adb install -t -g ../Krishivaas_Farmer.apk
            echo "Running tests..."
            cd test-project && npm run test

      # Collect Allure results
      - name: Collect test results
        if: always()
        run: |
          mkdir -p allure-results
          cp -r test-project/allure-results/* allure-results/ || echo "No results found"

      # Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      # Upload report as artifact
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: /allure-report