name: Android APK Testing with Emulator & Allure
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Set up Java (required for Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK (free)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Install Allure (free)
      - name: Set up Allure
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g allure-commandline

      # Start Android Emulator (free)
      - name: Launch Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33  # Latest stable Android version
          arch: x86_64
          profile: Pixel 5
          disable-animations: true
          script: |
            adb wait-for-device
            adb install -t ./Krishivaas_Farmer.apk
            adb shell mkdir -p /sdcard/Download/allure-results
            adb shell am instrument -w \
              -e listener com.krishivaas.allure.AllureAndroidListener \
              com.krishivaas.test/androidx.test.runner.AndroidJUnitRunner

      # Extract test results (free)
      - name: Get Allure Results
        run: |
          mkdir -p allure-results
          adb pull /sdcard/Download/allure-results ./allure-results || echo "No results found"

      # Generate report (free)
      - name: Generate Allure Report
        if: always()
        run: allure generate ./allure-results --clean -o ./report

      # Save report as artifact (free)
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report