name: Android CI Tests with Allure
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4

      # Java Environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle Installation (Added here)
      - name: Install Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.4

      # Node Environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Dependencies
      - name: Install npm packages
        run: npm install

      # Allure Setup
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # Firebase Setup
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
          gcloud auth activate-service-account --key-file=firebase-service-account.json
          gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      # Build APKs
      - name: Build APKs
        run: |
          ./gradlew assembleDebug
          ./gradlew assembleAndroidTest

      # Run Firebase Test Lab with local results
      - name: Run Tests on Firebase
        run: |
          gcloud firebase test android run \
            --app app/build/outputs/apk/debug/app-debug.apk \
            --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=Pixel6,version=34,locale=en,orientation=portrait \
            --type instrumentation \
            --directories-to-pull /sdcard/Download \
            --environment-variables clearPackageData=true \
            --timeout 20m

      # Pull test results from device (assuming tests output to /sdcard/Download)
      - name: Pull Test Results
        run: |
          adb devices
          adb pull /sdcard/Download/allure-results ./allure-results || echo "No results found"

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: |
          mkdir -p allure-report
          allure generate ./allure-results --clean -o allure-report

      # Deploy Report to GitHub Pages
      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true

      # Cleanup
      - name: Clean Up
        if: always()
        run: rm -f firebase-service-account.json