name: Android APK Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Proper Android SDK setup with ADB
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        

      # Start ADB server
      - name: Start ADB Server
        run: adb start-server

      # Allure setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Allure
        run: npm install -g allure-commandline

      # Prepare APK
      - name: Prepare APK
        run: |
          cp "./Krishivaas_Farmer.apk" ./app.apk

      # Install APK with retry logic
      - name: Install APK
        run: |
          # Wait for ADB to be fully ready
          adb wait-for-device
          # Install with retries in case of temporary failures
          for i in {1..3}; do
            if adb install -t ./app.apk; then
              echo "Installation succeeded"
              break
            else
              echo "Installation attempt $i failed, retrying..."
              sleep 5
            fi
          done

      # Verify installation
      - name: Verify Installation
        run: |
          adb shell pm list packages | grep com.krishivaas || echo "Package not found"

      # Run tests and collect Allure results
      - name: Run Tests
        run: |
          # Clear previous results
          rm -rf ./results
          mkdir -p ./results
          
          # Run your tests here (example command)
          # Replace with your actual test command
          adb shell am instrument -w -r -e debug false \
            -e class com.krishivaas.TestSuite \
            com.krishivaas.test/androidx.test.runner.AndroidJUnitRunner \
            | tee ./results/test-output.txt
          
          # Pull Allure results from device
          adb pull /sdcard/Download/allure-results ./results || echo "No results found"

      # Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate ./results --clean -o ./report
          
      # Upload report as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./report

      # Terminate Emulator
      - name: Terminate Emulator
        if: always()
        run: |
          adb -s emulator-5554 emu kill || true
          echo "Emulator terminated successfully"