name: Android APK Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Setup Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Allure setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Allure
        run: npm install -g allure-commandline

      # Firebase authentication (only needed if using Firebase Test Lab)
      - name: Authenticate Firebase
        if: false # Disabled since we're not using Firebase Test Lab
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-key.json
          gcloud auth activate-service-account --key-file=firebase-key.json
          gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      # Prepare APK
      - name: Prepare APK
        run: |
          cp "./Krishivaas_Farmer_RN(V1.3.60).apk" ./app.apk

      # Install APK
      - name: Install APK
        run: adb install -t ./app.apk

      # Run tests (using ADB commands instead of Firebase)
      - name: Run Tests
        run: |
          # Clear previous results
          rm -rf ./results
          mkdir -p ./results
          
          # Run your tests here (example commands)
          adb shell am instrument -w -r -e debug false \
            -e class com.krishivaas.TestSuite \
            com.krishivaas.test/androidx.test.runner.AndroidJUnitRunner \
            | tee ./results/test-output.txt
          
          # Pull Allure results from device
          adb pull /sdcard/Download/allure-results ./results || echo "No results found"

      # Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate ./results --clean -o ./report
          
      # Upload report as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      # Serve report (optional - for viewing in workflow summary)
      - name: Serve Allure Report
        if: always()
        run: |
          allure serve ./results