name: Run Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      # Java Setup
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Android SDK Setup
      - name: Set up Android Environment
        run: |
          # Accept licenses
          mkdir -p $ANDROID_HOME/licenses
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

          # Install required components
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator" "build-tools;34.0.0"
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH

      # Node Setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Dependencies
      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # Emulator Setup
      - name: Reset ADB Server
        run: |
          adb kill-server
          adb start-server

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          emulator-boot-timeout: 900
          script: echo "Emulator setup complete"

      # Emulator Readiness
      - name: Wait for Emulator
        timeout-minutes: 5
        run: |
          # Wait for device to be visible
          until adb devices | grep -q "emulator-.*device"; do
            sleep 5
            echo "Waiting for device to come online..."
          done

          # Unlock device
          adb shell input keyevent 82
          
          # Disable animations
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          
          # Wait for full boot
          until adb shell getprop sys.boot_completed | grep -q "1"; do
            sleep 5
            echo "Waiting for boot completion..."
          done

          # Verify connection
          adb devices
          adb shell getprop

      # Test Execution
      - name: Run tests
        timeout-minutes: 15
        run: npx wdio run wdio.conf.js

      # Reporting
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Deploy Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report